language: python
python:
  - '3.5'
install:
  - 'pip install -r requirements.txt'
  - 'python -m nltk.downloader "stopwords"'
script: 'python -m unittest'
after_success:
  - 'coverage run --include=\'./*\' test_td2.py'
  - 'codeclimate-test-reporter'
